# Generated by Django 4.1.6 on 2023-02-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.JSONField(blank=True, null=True)),
                ('pokemon_entries', models.JSONField(blank=True, null=True)),
                ('region', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abilities', models.JSONField(blank=True, null=True)),
                ('base_experience', models.IntegerField(max_length=10, null=True)),
                ('height', models.IntegerField(max_length=10, null=True)),
                ('species', models.JSONField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, null=True)),
                ('weight', models.IntegerField(max_length=10)),
            ],
        ),
    ]
